[package]
name = "fetch-input"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
nom = "8.0"
reqwest = { version = "0.12", features = ["blocking"] }
anyhow = "1.0"
